"""
OOD Benchmark Comparison Script

Tests multiple GNN models as unweighted (constant weight 1.0) guidance for the march solver
across size buckets generated by generate_ood_benchmark.py.

For each size bucket and each model:
  - Runs inference + solving on all problems in the bucket
  - If 5 consecutive timeouts occur → skip the rest of that bucket for that model
  - Records per-bucket per-model: num_solved, num_timed_out, num_skipped, avg_decisions, avg_time

Output: a single JSON file with nested structure:
    results[size_folder][model_name] = { num_solved, num_timed_out, num_skipped,
                                         avg_decisions, avg_time, total_problems }

Usage:
    python run_ood_comparison.py SATSolving/3-sat/ood_test \\
        --arienet_checkpoint runs/sat_arienet_3-sat_marginal_on_4000/checkpoints/model_best.pt \\
        --nsnet_checkpoint   runs/sat_nsnet_3-sat_marginal_on_4000/checkpoints/model_best.pt  \\
        --canonical_checkpoint models/arienet_backbone_canonical/best_model.pt                 \\
        --cooc_checkpoint      models/arienet_cooc/best_model.pt                                \\
        --extra_cooc_checkpoint ArieNetCoocA=models/arienet_cooc_a/best_model.pt                \\
        "--extra_cooc_checkpoint ArieNetCoocB=models/arienet_cooc_b/best_model.pt \\\n        --extra_backbone_checkpoint BackboneNoLSP=models/arienet_backbone_nolsp/best_model.pt \\\n        --extra_backbone_checkpoint BackboneWithLSP=models/arienet_backbone/best_model.pt
"""

import os
import sys
import glob
import json
import time
import argparse
import tempfile
import subprocess
import numpy as np
from datetime import datetime
from pathlib import Path

import torch
import torch.nn.functional as F
from torch_geometric.loader import DataLoader

# ---------------------------------------------------------------------------
# Solver paths
# ---------------------------------------------------------------------------
MARCH_UNWEIGHTED_PATH = "./march_weighted/march_nh"
MARCH_UNMODIFIED_PATH = "./march_unmodified/march/march_nh"


# ---------------------------------------------------------------------------
# Model names that this script knows about
# ---------------------------------------------------------------------------
ALL_MODELS = ["NSNet", "ArieNet", "Backbone", "BackboneCanonical", "BackboneUP",
              "ArieNetCooc", "MarchUnmodified"]

# Module-level registry of extra backbone model names (populated in main()).
_EXTRA_BACKBONE_NAMES: set = set()
# Module-level registry of RLAF model names (populated in main()).
_RLAF_MODEL_NAMES: set = set()
# Module-level registry of RLAF model names (populated in main()).
_RLAF_MODEL_NAMES: set = set()


def is_cooc_model(model_name):
    return model_name == "ArieNetCooc" or model_name.startswith("ArieNetCooc_")


def is_rlaf_model(model_name):
    return model_name in _RLAF_MODEL_NAMES


def is_rlaf_model(model_name):
    return model_name in _RLAF_MODEL_NAMES


def is_backbone_model(model_name):
    """True for the built-in 'Backbone' or any extra backbone registered via --extra_backbone_checkpoint."""
    return model_name == "Backbone" or model_name in _EXTRA_BACKBONE_NAMES


def parse_extra_backbone_args(extra_args):
    """
    Parse repeatable --extra_backbone_checkpoint values.
    Accepted formats:
      - NAME=PATH
      - PATH  (auto-named as Backbone_2, Backbone_3, ...)
    Returns dict model_name -> checkpoint_path.
    """
    extra_map = {}
    next_idx = 2

    for raw in extra_args or []:
        item = raw.strip()
        if not item:
            continue

        if "=" in item:
            name, path = item.split("=", 1)
            name = name.strip()
            path = path.strip()
            if not name:
                raise ValueError(f"Invalid --extra_backbone_checkpoint '{raw}': empty model name")
            if name in extra_map:
                raise ValueError(f"Duplicate extra backbone model name: {name}")
            extra_map[name] = path
        else:
            while True:
                auto_name = f"Backbone_{next_idx}"
                next_idx += 1
                if auto_name not in extra_map:
                    break
            extra_map[auto_name] = item

    return extra_map


def parse_extra_cooc_args(extra_args):
    """
    Parse repeatable --extra_cooc_checkpoint values.
    Accepted formats:
      - NAME=PATH
      - PATH  (auto-named as ArieNetCooc_2, ArieNetCooc_3, ...)
    Returns dict model_name -> checkpoint_path.
    """
    extra_map = {}
    next_idx = 2

    for raw in extra_args or []:
        item = raw.strip()
        if not item:
            continue

        if "=" in item:
            name, path = item.split("=", 1)
            name = name.strip()
            path = path.strip()
            if not name:
                raise ValueError(f"Invalid --extra_cooc_checkpoint '{raw}': empty model name")
            if name in extra_map:
                raise ValueError(f"Duplicate extra CoOC model name: {name}")
            extra_map[name] = path
        else:
            while True:
                auto_name = f"ArieNetCooc_{next_idx}"
                next_idx += 1
                if auto_name not in extra_map:
                    break
            extra_map[auto_name] = item

    return extra_map


def parse_rlaf_args(extra_args):
    """
    Parse repeatable --rlaf_checkpoint values.
    Accepted formats:
      - NAME=PATH
      - PATH  (auto-named as RLAF, RLAF_2, RLAF_3, ...)
    Returns dict model_name -> checkpoint_path.
    """
    extra_map = {}
    next_idx = 2
    first = True

    for raw in extra_args or []:
        item = raw.strip()
        if not item:
            continue

        if "=" in item:
            name, path = item.split("=", 1)
            name = name.strip()
            path = path.strip()
            if not name:
                raise ValueError(f"Invalid --rlaf_checkpoint '{raw}': empty model name")
            if name in extra_map:
                raise ValueError(f"Duplicate RLAF model name: {name}")
            extra_map[name] = path
        else:
            if first:
                auto_name = "RLAF"
                first = False
            else:
                while True:
                    auto_name = f"RLAF_{next_idx}"
                    next_idx += 1
                    if auto_name not in extra_map:
                        break
            extra_map[auto_name] = item

    return extra_map

def load_dimacs_cnf(filepath):
    clauses = []
    num_vars = 0
    with open(filepath, "r") as f:
        for line in f:
            line = line.strip()
            if line.startswith("c") or line.startswith("%") or line.startswith("0"):
                continue
            elif line.startswith("p"):
                parts = line.split()
                num_vars = int(parts[2])
            else:
                clause = [int(x) for x in line.split() if int(x) != 0]
                if clause:
                    clauses.append(clause)
    return clauses, num_vars


def cnf_to_dimacs_unweighted(clauses, num_vars, phase_hints):
    """
    Produce a DIMACS string with 'c weight' guidance at constant weight=1.0.
    phase_hints: np.ndarray [num_vars] of 0.0/1.0
    """
    lines = [f"p cnf {num_vars} {len(clauses)}"]
    params = ["c weight"]
    for i in range(num_vars):
        sgn = 1 if phase_hints[i] > 0 else -1
        params.append(f"{sgn * 1.0:.4f}")
    lines.append(" ".join(params))
    for clause in clauses:
        lines.append(" ".join(map(str, clause)) + " 0")
    return "\n".join(lines)


def solve_with_march_unweighted(clauses, num_vars, phase_hints, seed, timeout):
    """
    Run march_weighted with constant-weight (1.0) guidance.
    Returns dict with keys: Result, decisions, CPU_time
    """
    dimacs_str = cnf_to_dimacs_unweighted(clauses, num_vars, phase_hints)

    with tempfile.NamedTemporaryFile(mode="w", suffix=".cnf", delete=False) as f:
        f.write(dimacs_str)
        tmp_path = f.name

    try:
        call = [MARCH_UNWEIGHTED_PATH, tmp_path]
        if seed is not None and seed > 0:
            call.append(f"-seed={seed}")

        result = subprocess.run(
            call, capture_output=True, text=True, timeout=timeout
        )
        return _parse_march(result.stdout)
    except subprocess.TimeoutExpired:
        return {"Result": "TIMEOUT", "decisions": -1, "CPU_time": float(timeout)}
    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass


def solve_with_march_unmodified(filepath, timeout):
    """
    Run the unmodified march solver directly on a CNF file (no GNN guidance).
    Returns dict with keys: Result, decisions, CPU_time
    """
    try:
        result = subprocess.run(
            [MARCH_UNMODIFIED_PATH, filepath],
            capture_output=True, text=True, timeout=timeout
        )
        return _parse_march(result.stdout)
    except subprocess.TimeoutExpired:
        return {"Result": "TIMEOUT", "decisions": -1, "CPU_time": float(timeout)}


def _parse_march(stdout):
    stats = {"Result": "UNKNOWN", "decisions": -1, "CPU_time": -1.0}
    for line in stdout.splitlines():
        line = line.strip()
        upper = line.upper()
        if "SATISFIABLE" in upper and "UNSATISFIABLE" not in upper:
            stats["Result"] = "SATISFIABLE"
        elif "UNSATISFIABLE" in upper:
            stats["Result"] = "UNSATISFIABLE"
        if line.startswith("c decisions"):
            try:
                stats["decisions"] = int(line.split(":")[1].strip().split()[0])
            except (IndexError, ValueError):
                pass
        if "time" in line.lower() and ":" in line:
            try:
                stats["CPU_time"] = float(line.split(":")[1].strip().split()[0])
            except (IndexError, ValueError):
                pass
    return stats


# ---------------------------------------------------------------------------
# Model loading
# ---------------------------------------------------------------------------

def load_model(model_name, checkpoint_path, device):
    """Load model and return (model, model_type_tag)."""
    from src.nsnet.utils.options import add_model_options
    from src.nsnet.models.nsnet import NSNet
    from src.nsnet.models.arienet import ArieNet

    if model_name == "NSNet":
        import argparse as _ap
        p = _ap.ArgumentParser()
        add_model_options(p)
        opts = p.parse_args([])
        opts.model = "NSNet"
        opts.device = device
        opts.task = "satisfiability"
        model = NSNet(opts)
        ckpt = torch.load(checkpoint_path, map_location=device)
        model.load_state_dict(ckpt["state_dict"], strict=False)

    elif model_name == "ArieNet":
        import argparse as _ap
        p = _ap.ArgumentParser()
        add_model_options(p)
        opts = p.parse_args([])
        opts.model = "ArieNet"
        opts.device = device
        opts.task = "satisfiability"
        model = ArieNet(opts)
        ckpt = torch.load(checkpoint_path, map_location=device)
        model.load_state_dict(ckpt["state_dict"], strict=False)

    elif is_backbone_model(model_name):
        from train_arienet_backbone import ArieNetBackbone
        ckpt = torch.load(checkpoint_path, map_location=device)
        ckpt_args = ckpt.get("args", {})
        no_lsp = ckpt_args.get("no_precomputed_local_sat", False)
        model = ArieNetBackbone(device=device, no_precomputed_local_sat=no_lsp)
        model.load_state_dict(ckpt["model_state_dict"], strict=False)

    elif model_name == "BackboneCanonical":
        from train_arienet_backbone import ArieNetBackbone
        model = ArieNetBackbone(device=device, use_subgraph_features=True, subgraph_dim=32)
        ckpt = torch.load(checkpoint_path, map_location=device)
        model.load_state_dict(ckpt["model_state_dict"], strict=False)

    elif model_name == "BackboneUP":
        from train_arienet_backbone import ArieNetBackbone
        model = ArieNetBackbone(device=device, use_up_features=True)
        ckpt = torch.load(checkpoint_path, map_location=device)
        model.load_state_dict(ckpt["model_state_dict"], strict=False)

    elif is_cooc_model(model_name):
        from src.nsnet.models.arienet import ArieNetCooc
        import argparse as _ap
        ckpt = torch.load(checkpoint_path, map_location=device)
        ckpt_args = ckpt["args"]
        cooc_opts = _ap.Namespace(
            dim=ckpt_args.dim,
            n_rounds=ckpt_args.n_rounds,
            n_mlp_layers=ckpt_args.n_mlp_layers,
            activation="relu",
            device=device,
            task="satisfiability",
        )
        model = ArieNetCooc(cooc_opts)
        model.load_state_dict(ckpt["model_state_dict"])

    elif is_rlaf_model(model_name):
        import sys as _sys
        _sys.path.insert(0, os.path.join(os.path.dirname(__file__), "src"))
        from omegaconf import OmegaConf
        from nsnet.models.arienet_rlaf import ArieNetRLAF, ArieNetRLAFCooc
        # Load config.yaml from the checkpoint directory if present
        ckpt_dir = os.path.dirname(os.path.abspath(checkpoint_path))
        cfg_file = os.path.join(ckpt_dir, "config.yaml")
        cfg = OmegaConf.load(cfg_file) if os.path.exists(cfg_file) else None
        model_kwargs = dict(dim=128, n_rounds=26, n_mlp_layers=3)
        use_cooc = False
        if cfg is not None:
            model_kwargs["dim"] = cfg.model.dim
            model_kwargs["n_rounds"] = cfg.model.n_rounds
            model_kwargs["n_mlp_layers"] = cfg.model.n_mlp_layers
            model_kwargs["no_precomputed_local_sat"] = cfg.model.no_precomputed_local_sat
            model_kwargs["use_up_features"] = cfg.model.use_up_features
            use_cooc = getattr(cfg, "use_cooc", False)
        ModelCls = ArieNetRLAFCooc if use_cooc else ArieNetRLAF
        model = ModelCls(**model_kwargs)
        model.load_state_dict(torch.load(checkpoint_path, map_location=device))

    else:
        raise ValueError(f"Unknown model: {model_name}")

    model.to(device)
    model.eval()
    return model


def build_dataloader(model_name, cnf_dir, batch_size, num_workers, cooc_process_workers=1,
                     backbone_process_workers=4):
    """Return (dataloader, list_of_cnf_files)."""
    if model_name in ("NSNet", "ArieNet"):
        from src.nsnet.utils.dataloader import get_dataloader
        import argparse as _ap
        from src.nsnet.utils.options import add_model_options

        p = _ap.ArgumentParser()
        add_model_options(p)
        opts = p.parse_args([])
        opts.model = model_name
        opts.device = torch.device("cpu")
        opts.task = "satisfiability"
        opts.batch_size = batch_size
        opts.num_workers = num_workers
        opts.pin_memory = False
        opts.test_dir = cnf_dir

        loader = get_dataloader(cnf_dir, opts, "test")
        files = sorted(glob.glob(os.path.join(cnf_dir, "*.cnf")))
        return loader, [os.path.abspath(f) for f in files]

    elif is_backbone_model(model_name):
        from train_arienet_backbone import BackboneBPGDataset
        dataset = BackboneBPGDataset(cnf_dir, num_process_workers=backbone_process_workers)
        loader = DataLoader(dataset, batch_size=batch_size, shuffle=False,
                            num_workers=num_workers, pin_memory=False)
        return loader, [os.path.abspath(f) for f in dataset.cnf_files]

    elif model_name == "BackboneCanonical":
        from train_arienet_backbone_canonical import CanonicalBackboneBPGDataset
        # compute_subgraphs=False: the canonical subgraph feature computation runs a
        # brute-force 2^k truth-table enumeration per BPG edge (k = size of 2-hop
        # neighbourhood, easily 10-20 vars for OOD instances).  That makes processing
        # infeasibly slow for large n.  With compute_subgraphs=False the BPG is still
        # built correctly; the model's subgraph branch is simply skipped (it guards
        # with `if hasattr(data, 'subgraphs_p1') and data.subgraphs_p1 is not None`).
        # This means BackboneCanonical runs as a plain Backbone for OOD evaluation.
        dataset = CanonicalBackboneBPGDataset(cnf_dir, compute_subgraphs=False)
        loader = DataLoader(dataset, batch_size=batch_size, shuffle=False,
                            num_workers=num_workers, pin_memory=False)
        return loader, [os.path.abspath(f) for f in dataset.cnf_files]

    elif model_name == "BackboneUP":
        from train_arienet_backbone import BackboneBPGDataset
        # use_up_features=True triggers per-literal UP feature precomputation via pysat.
        # Backbone labels (backbones.pkl) are not needed for inference; the dataset
        # handles a missing backbones.pkl gracefully (warns, sets all y=2).
        # Default to single-threaded to avoid pysat C-extension deadlocks under fork.
        dataset = BackboneBPGDataset(cnf_dir, use_up_features=True,
                                     num_process_workers=backbone_process_workers)
        loader = DataLoader(dataset, batch_size=batch_size, shuffle=False,
                            num_workers=num_workers, pin_memory=False)
        return loader, [os.path.abspath(f) for f in dataset.cnf_files]

    elif is_cooc_model(model_name):
        from train_arienet_cooc import CoocBPGDataset
        dataset = CoocBPGDataset(cnf_dir, process_workers=cooc_process_workers)
        loader = DataLoader(dataset, batch_size=batch_size, shuffle=False,
                            num_workers=num_workers, pin_memory=False)
        return loader, [os.path.abspath(f) for f in dataset.cnf_files]

    elif is_rlaf_model(model_name):
        import sys as _sys
        _sys.path.insert(0, os.path.join(os.path.dirname(__file__), "src"))
        from nsnet.datasets.rlaf_dataset import RLAFBPGDataset, _collate_skip_none
        dataset = RLAFBPGDataset(
            path=cnf_dir,
            num_workers=backbone_process_workers,
        )
        loader = DataLoader(dataset, batch_size=batch_size, shuffle=False,
                            num_workers=num_workers, pin_memory=False,
                            collate_fn=_collate_skip_none)
        return loader, [os.path.abspath(f) for f in dataset.cnf_files]

    else:
        raise ValueError(f"Unknown model: {model_name}")


def run_inference(model, model_name, loader, device):
    """
    Run the model over the full dataloader.
    Returns list of np.ndarray [n_vars] with phase hints (0 or 1).
    RLAF models should use run_rlaf_inference instead.
    """
    phase_hints_list = []

    for data in loader:
        data = data.to(device)
        with torch.no_grad():
            if model_name in ("Backbone", "BackboneCanonical", "BackboneUP") or is_backbone_model(model_name):
                v_logits = model(data)
                v_probs = F.softmax(v_logits, dim=1)
            else:
                v_probs = model(data)  # already softmax

        # Determine v_sizes per graph in batch.
        # ArieNet uses BPG → data.n_literals ; NSNet uses OldBPG → data.l_size
        # Backbone, BackboneCanonical and ArieNetCooc also use BPG → data.n_literals
        if model_name in ("ArieNet", "Backbone", "BackboneCanonical", "BackboneUP") or is_backbone_model(model_name) or is_cooc_model(model_name):
            raw = data.n_literals
            if isinstance(raw, torch.Tensor):
                v_sizes = (raw / 2).int().tolist()
            elif isinstance(raw, list):
                v_sizes = [int(n / 2) for n in raw]
            else:
                v_sizes = [int(raw / 2)]
        elif model_name == "NSNet":
            raw = data.l_size
            if isinstance(raw, torch.Tensor):
                v_sizes = (raw / 2).int().tolist()
            elif isinstance(raw, list):
                v_sizes = [int(n / 2) for n in raw]
            else:
                v_sizes = [int(raw / 2)]
        else:
            raise ValueError(f"Unknown model: {model_name}")

        offset = 0
        for v_size in v_sizes:
            probs = v_probs[offset : offset + v_size].cpu().numpy()
            phase = (probs[:, 1] > probs[:, 0]).astype(float)
            phase_hints_list.append(phase)
            offset += v_size

    return phase_hints_list


def run_rlaf_inference(model, loader, device, scale_sigma=0.1):
    """Run an RLAF model and return var_params as list of np.ndarray [n_vars, 2].

    Uses the modal (deterministic) policy: phase = sign(rho), weight = exp(mu).
    Column 0 = rho (phase logit), column 1 = weight (log-normal mean).
    """
    import sys as _sys
    _sys.path.insert(0, os.path.join(os.path.dirname(__file__), "src"))
    from nsnet.policy import policy_bpg as policy

    var_params_list = []
    model.eval()
    with torch.no_grad():
        for data in loader:
            if data is None:
                continue
            data = data.to(device)
            y_var = model(data)  # [total_vars_in_batch, 2]

            n_lits = data.n_literals
            if isinstance(n_lits, torch.Tensor):
                n_vars_list = (n_lits // 2).int().tolist()
            elif isinstance(n_lits, list):
                n_vars_list = [int(n // 2) for n in n_lits]
            else:
                n_vars_list = [int(n_lits // 2)]

            # Modal var_params: shape [1, total_vars, 2] → squeeze
            params_modal = policy.mode(y_var.float(), scale_sigma=scale_sigma).squeeze(0)
            params_np = params_modal.cpu().numpy()

            offset = 0
            for n_v in n_vars_list:
                var_params_list.append(params_np[offset:offset + n_v])
                offset += n_v

    return var_params_list


def run_rlaf_inference(model, loader, device, scale_sigma=0.1):
    """Run an RLAF model and return var_params as list of np.ndarray [n_vars, 2].

    Uses the modal (deterministic) policy: phase = sign(rho), weight = exp(mu).
    """
    import sys as _sys
    _sys.path.insert(0, os.path.join(os.path.dirname(__file__), "src"))
    from nsnet.policy import policy_bpg as policy

    var_params_list = []
    model.eval()
    with torch.no_grad():
        for data in loader:
            if data is None:
                continue
            data = data.to(device)
            y_var = model(data)  # [total_vars_in_batch, 2]

            # Compute n_vars per graph
            n_lits = data.n_literals
            if isinstance(n_lits, torch.Tensor):
                n_vars_list = (n_lits // 2).int().tolist()
            elif isinstance(n_lits, list):
                n_vars_list = [int(n // 2) for n in n_lits]
            else:
                n_vars_list = [int(n_lits // 2)]

            # Modal var_params: shape [1, total_vars, 2] → squeeze
            params_modal = policy.mode(y_var.float(), scale_sigma=scale_sigma).squeeze(0)  # [total_vars, 2]
            params_np = params_modal.cpu().numpy()  # [total_vars, 2]

            offset = 0
            for n_v in n_vars_list:
                var_params_list.append(params_np[offset:offset + n_v])
                offset += n_v

    return var_params_list


def solve_with_march_weighted(clauses, num_vars, var_params, seed, timeout):
    """Run march_weighted with full (phase + weight) guidance from an RLAF model."""
    from nsnet.policy.evaluate_bpg import _make_dimacs
    dimacs_str = _make_dimacs(clauses, var_params)

    with tempfile.NamedTemporaryFile(mode="w", suffix=".cnf", delete=False) as f:
        f.write(dimacs_str)
        tmp_path = f.name

    try:
        call = [MARCH_UNWEIGHTED_PATH, tmp_path]  # same march_nh binary, weighted format
        if seed is not None and seed > 0:
            call.append(f"-seed={seed}")
        result = subprocess.run(call, capture_output=True, text=True, timeout=timeout)
        return _parse_march(result.stdout)
    except subprocess.TimeoutExpired:
        return {"Result": "TIMEOUT", "decisions": -1, "CPU_time": float(timeout)}
    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass


def evaluate_bucket(model, model_name, cnf_dir, batch_size, num_workers,
                    device, timeout, seed, consecutive_timeout_limit,
                    cooc_process_workers=1, backbone_process_workers=4):
    """
    Run one model on one size bucket.
    Returns dict: num_solved, num_timed_out, num_skipped, avg_decisions, avg_time, total_problems
    """
    print(f"    Building dataloader for {model_name} ...")
    try:
        loader, all_files = build_dataloader(
            model_name, cnf_dir, batch_size, num_workers,
            cooc_process_workers=cooc_process_workers,
            backbone_process_workers=backbone_process_workers,
        )
    except Exception as e:
        print(f"    [ERROR] Could not build dataloader: {e}")
        return None

    n_total = len(all_files)
    if n_total == 0:
        print(f"    [WARN] No CNF files found in {cnf_dir}")
        return None

    print(f"    Running inference on {n_total} instances ...")
    try:
        if is_rlaf_model(model_name):
            guidance_list = run_rlaf_inference(model, loader, device)
        else:
            guidance_list = run_inference(model, model_name, loader, device)
    except Exception as e:
        print(f"    [ERROR] Inference failed: {e}")
        return None

    assert len(guidance_list) == n_total, (
        f"Mismatch: {len(guidance_list)} predictions vs {n_total} files"
    )

    solve_mode = "weighted (RLAF)" if is_rlaf_model(model_name) else "unweighted"
    print(f"    Solving with march ({solve_mode} guidance, timeout={timeout}s) ...")
    num_solved = 0
    num_timed_out = 0
    num_skipped = 0
    decisions_list = []
    times_list = []

    consecutive_timeouts = 0

    for idx, (filepath, guidance) in enumerate(zip(all_files, guidance_list)):
        # Check consecutive timeout early-exit
        if consecutive_timeouts >= consecutive_timeout_limit:
            remaining = n_total - idx
            num_skipped += remaining
            print(f"    [{idx}/{n_total}] {consecutive_timeout_limit} consecutive timeouts — "
                  f"skipping remaining {remaining} instances.")
            break

        clauses, num_vars = load_dimacs_cnf(filepath)
        t_start = time.time()
        if is_rlaf_model(model_name):
            stats = solve_with_march_weighted(clauses, num_vars, guidance, seed, timeout)
        else:
            stats = solve_with_march_unweighted(clauses, num_vars, guidance, seed, timeout)
        wall_time = time.time() - t_start

        result = stats.get("Result", "UNKNOWN")

        if result == "SATISFIABLE":
            num_solved += 1
            consecutive_timeouts = 0
        elif result == "TIMEOUT":
            num_timed_out += 1
            consecutive_timeouts += 1
        else:
            # UNSATISFIABLE or UNKNOWN — count as solved (decided), reset streak
            num_solved += 1
            consecutive_timeouts = 0

        dec = stats.get("decisions", -1)
        cpu_t = stats.get("CPU_time", -1.0)
        if dec > 0:
            decisions_list.append(dec)
        # Use wall time if solver didn't report CPU time
        times_list.append(cpu_t if cpu_t > 0 else wall_time)

        if (idx + 1) % 10 == 0 or (idx + 1) == n_total:
            print(f"    [{idx + 1}/{n_total}] solved={num_solved} "
                  f"timed_out={num_timed_out} skipped={num_skipped}", end="\r")

    print()  # newline after \r progress

    return {
        "total_problems": n_total,
        "num_solved": num_solved,
        "num_timed_out": num_timed_out,
        "num_skipped": num_skipped,
        "avg_decisions": float(np.mean(decisions_list)) if decisions_list else None,
        "avg_time": float(np.mean(times_list)) if times_list else None,
    }


# ---------------------------------------------------------------------------
# Unmodified march baseline evaluation (no GNN)
# ---------------------------------------------------------------------------

def evaluate_bucket_unmodified(cnf_dir, timeout, consecutive_timeout_limit):
    """
    Run the unmodified march solver on every CNF file in cnf_dir with no GNN
    guidance (pure solver baseline).
    Returns the same dict shape as evaluate_bucket().
    """
    all_files = sorted(glob.glob(os.path.join(cnf_dir, "*.cnf")))
    n_total = len(all_files)
    if n_total == 0:
        print(f"    [WARN] No CNF files found in {cnf_dir}")
        return None

    print(f"    Solving {n_total} instances with unmodified march (timeout={timeout}s) ...")

    num_solved = 0
    num_timed_out = 0
    num_skipped = 0
    decisions_list = []
    times_list = []
    consecutive_timeouts = 0

    for idx, filepath in enumerate(all_files):
        if consecutive_timeouts >= consecutive_timeout_limit:
            remaining = n_total - idx
            num_skipped += remaining
            print(f"    [{idx}/{n_total}] {consecutive_timeout_limit} consecutive timeouts — "
                  f"skipping remaining {remaining} instances.")
            break

        t_start = time.time()
        stats = solve_with_march_unmodified(os.path.abspath(filepath), timeout)
        wall_time = time.time() - t_start

        result = stats.get("Result", "UNKNOWN")
        if result == "TIMEOUT":
            num_timed_out += 1
            consecutive_timeouts += 1
        else:
            num_solved += 1
            consecutive_timeouts = 0

        dec = stats.get("decisions", -1)
        cpu_t = stats.get("CPU_time", -1.0)
        if dec > 0:
            decisions_list.append(dec)
        times_list.append(cpu_t if cpu_t > 0 else wall_time)

        if (idx + 1) % 10 == 0 or (idx + 1) == n_total:
            print(f"    [{idx + 1}/{n_total}] solved={num_solved} "
                  f"timed_out={num_timed_out} skipped={num_skipped}", end="\r")

    print()

    return {
        "total_problems": n_total,
        "num_solved": num_solved,
        "num_timed_out": num_timed_out,
        "num_skipped": num_skipped,
        "avg_decisions": float(np.mean(decisions_list)) if decisions_list else None,
        "avg_time": float(np.mean(times_list)) if times_list else None,
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="OOD benchmark: test models on increasingly large 3-SAT instances."
    )
    parser.add_argument(
        "ood_dir",
        type=str,
        help="Root OOD benchmark directory (e.g. SATSolving/3-sat/ood_test)",
    )

    # Model checkpoints (all optional — models without checkpoints are skipped)
    parser.add_argument("--nsnet_checkpoint", type=str, default=None,
                        help="Path to NSNet checkpoint")
    parser.add_argument("--arienet_checkpoint", type=str, default=None,
                        help="Path to ArieNet checkpoint")
    parser.add_argument("--backbone_checkpoint", type=str, default=None,
                        help="Path to plain ArieNetBackbone checkpoint (supports "
                             "--no_precomputed_local_sat checkpoints via saved args)")
    parser.add_argument(
        "--extra_backbone_checkpoint",
        action="append",
        default=[],
        help=(
            "Additional Backbone model checkpoint. Repeatable. Formats: "
            "NAME=PATH or PATH (auto-named Backbone_2, Backbone_3, ...). "
            "Useful to compare e.g. a model trained with and without "
            "--no_precomputed_local_sat side by side."
        ),
    )
    parser.add_argument("--canonical_checkpoint", type=str, default=None,
                        help="Path to BackboneCanonical checkpoint")
    parser.add_argument("--backbone_up_checkpoint", type=str, default=None,
                        help="Path to BackboneUP checkpoint (ArieNetBackbone trained with "
                             "--use_up_features; requires python-sat at inference time)")
    parser.add_argument("--cooc_checkpoint", type=str, default=None,
                        help="Path to ArieNetCooc checkpoint")
    parser.add_argument(
        "--extra_cooc_checkpoint",
        action="append",
        default=[],
        help=(
            "Additional CoOC model checkpoint. Repeatable. Formats: "
            "NAME=PATH or PATH (auto-named ArieNetCooc_2, ArieNetCooc_3, ...)."
        ),
    )
    parser.add_argument(
        "--rlaf_checkpoint",
        action="append",
        default=[],
        help=(
            "RLAF model checkpoint (ArieNetRLAF / ArieNetRLAFCooc trained with "
            "train_arienet_rlaf.py). Repeatable. Formats: "
            "NAME=PATH or PATH (auto-named RLAF, RLAF_2, ...). "
            "Uses march_weighted with full phase+weight guidance."
        ),
    )
    parser.add_argument("--march_unmodified", action="store_true", default=False,
                        help="Include unmodified march solver as a baseline (no GNN guidance)")
    parser.add_argument("--march_unmodified_path", type=str, default=None,
                        help="Override path to unmodified march binary")

    # Solver / runtime settings
    parser.add_argument("--timeout", type=int, default=300,
                        help="Per-instance solver timeout in seconds (default: 300 = 5 min)")
    parser.add_argument("--consecutive_timeout_limit", type=int, default=5,
                        help="Skip rest of size bucket after this many consecutive timeouts (default: 5)")
    parser.add_argument("--seed", type=int, default=1,
                        help="Random seed for the solver (default: 1)")
    parser.add_argument("--batch_size", type=int, default=1,
                        help="Batch size for GNN inference (default: 1; increase for small instances)")
    parser.add_argument("--num_workers", type=int, default=0,
                        help="DataLoader workers (default: 0)")
    parser.add_argument("--cooc_process_workers", type=int, default=1,
                        help="CoOC dataset preprocessing workers (default: 1; safer on WSL)")
    parser.add_argument("--backbone_process_workers", type=int, default=1,
                        help="Backbone/BackboneUP dataset preprocessing workers (default: 1; "
                             "set to 1 to avoid pysat C-extension deadlocks under fork)")
    parser.add_argument("--march_path", type=str, default=None,
                        help="Override path to march_nh binary")

    # Output
    parser.add_argument("--out_file", type=str, default=None,
                        help="Output JSON file path (default: auto-timestamped)")

    args = parser.parse_args()

    # Override march paths if requested
    if args.march_path:
        global MARCH_UNWEIGHTED_PATH
        MARCH_UNWEIGHTED_PATH = args.march_path
    if args.march_unmodified_path:
        global MARCH_UNMODIFIED_PATH
        MARCH_UNMODIFIED_PATH = args.march_unmodified_path

    # Build list of (model_name, checkpoint_path) to run
    model_ckpts = {
        "NSNet": args.nsnet_checkpoint,
        "ArieNet": args.arienet_checkpoint,
        "Backbone": args.backbone_checkpoint,
        "BackboneCanonical": args.canonical_checkpoint,
        "BackboneUP": args.backbone_up_checkpoint,
        "ArieNetCooc": args.cooc_checkpoint,
    }

    try:
        extra_cooc_models = parse_extra_cooc_args(args.extra_cooc_checkpoint)
    except ValueError as e:
        print(f"[ERROR] {e}")
        sys.exit(1)

    try:
        extra_backbone_models = parse_extra_backbone_args(args.extra_backbone_checkpoint)
    except ValueError as e:
        print(f"[ERROR] {e}")
        sys.exit(1)

    try:
        rlaf_models = parse_rlaf_args(args.rlaf_checkpoint)
    except ValueError as e:
        print(f"[ERROR] {e}")
        sys.exit(1)

    overlapping = set(model_ckpts).intersection(extra_cooc_models).union(
        set(model_ckpts).intersection(extra_backbone_models),
        set(extra_cooc_models).intersection(extra_backbone_models),
        set(rlaf_models).intersection(model_ckpts),
        set(rlaf_models).intersection(extra_cooc_models),
        set(rlaf_models).intersection(extra_backbone_models),
    )
    if overlapping:
        print("[ERROR] Duplicate model names across built-in / extra CoOC / extra Backbone / RLAF: "
              f"{sorted(overlapping)}")
        sys.exit(1)

    model_ckpts.update(extra_cooc_models)
    model_ckpts.update(extra_backbone_models)
    model_ckpts.update(rlaf_models)

    # Register extra backbone names so is_backbone_model() recognises them.
    _EXTRA_BACKBONE_NAMES.update(extra_backbone_models.keys())
    # Register RLAF model names so is_rlaf_model() recognises them.
    _RLAF_MODEL_NAMES.update(rlaf_models.keys())

    active_models = {k: v for k, v in model_ckpts.items() if v is not None}
    if args.march_unmodified:
        active_models["MarchUnmodified"] = "(no checkpoint)"

    if not active_models:
        print("[ERROR] No model checkpoints provided. Use --nsnet_checkpoint, "
              "--arienet_checkpoint, --canonical_checkpoint, --cooc_checkpoint, "
              "or --march_unmodified.")
        sys.exit(1)

    # Discover size buckets (sorted by variable count)
    ood_dir = os.path.abspath(args.ood_dir)
    buckets = sorted(
        [d for d in os.listdir(ood_dir) if os.path.isdir(os.path.join(ood_dir, d))],
        key=lambda x: int(x.lstrip("n")) if x.lstrip("n").isdigit() else 0,
    )
    if not buckets:
        print(f"[ERROR] No size bucket folders found in {ood_dir}")
        sys.exit(1)

    print("=" * 70)
    print("OOD BENCHMARK COMPARISON")
    print("=" * 70)
    print(f"  OOD dir          : {ood_dir}")
    print(f"  Size buckets     : {buckets}")
    print(f"  Models           : {list(active_models.keys())}")
    print(f"  Timeout          : {args.timeout}s per instance")
    print(f"  Consec. timeout  : skip after {args.consecutive_timeout_limit}")
    print(f"  Seed             : {args.seed}")
    print("=" * 70)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"  Device           : {device}\n")

    # Results structure: results[bucket][model_name] = {...}
    results = {
        "timestamp": datetime.now().isoformat(),
        "ood_dir": ood_dir,
        "timeout": args.timeout,
        "consecutive_timeout_limit": args.consecutive_timeout_limit,
        "seed": args.seed,
        "models": list(active_models.keys()),
        "checkpoints": active_models,
        "sizes": {},
    }

    # Pre-load all models once (avoids repeated checkpoint loading)
    print("Loading models...")
    loaded_models = {}
    for model_name, ckpt_path in active_models.items():
        if model_name == "MarchUnmodified":
            loaded_models[model_name] = "__unmodified_march__"
            print(f"  ✓ MarchUnmodified (no GNN, direct solver baseline)")
            continue
        print(f"  Loading {model_name} from {ckpt_path} ...")
        try:
            loaded_models[model_name] = load_model(model_name, ckpt_path, device)
            print(f"  ✓ {model_name} loaded")
        except Exception as e:
            print(f"  ✗ {model_name} FAILED to load: {e}")
            loaded_models[model_name] = None
    print()

    # Determine output file
    if args.out_file is None:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        args.out_file = f"ood_results_{ts}.json"

    # -----------------------------------------------------------------------
    # Main loop: iterate buckets × models
    # -----------------------------------------------------------------------
    for bucket in buckets:
        bucket_dir = os.path.join(ood_dir, bucket)
        cnf_count = len(glob.glob(os.path.join(bucket_dir, "*.cnf")))
        print(f"\n{'='*70}")
        print(f"SIZE BUCKET: {bucket}  ({cnf_count} CNF files)")
        print(f"{'='*70}")

        results["sizes"][bucket] = {}

        for model_name, model in loaded_models.items():
            if model is None:
                print(f"  [{model_name}] Skipped (failed to load).")
                results["sizes"][bucket][model_name] = {"error": "model load failed"}
                continue

            print(f"\n  >> {model_name}")
            t_bucket_start = time.time()

            if model_name == "MarchUnmodified":
                bucket_result = evaluate_bucket_unmodified(
                    cnf_dir=bucket_dir,
                    timeout=args.timeout,
                    consecutive_timeout_limit=args.consecutive_timeout_limit,
                )
            else:
                bucket_result = evaluate_bucket(
                    model=model,
                    model_name=model_name,
                    cnf_dir=bucket_dir,
                    batch_size=args.batch_size,
                    num_workers=args.num_workers,
                    device=device,
                    timeout=args.timeout,
                    seed=args.seed,
                    consecutive_timeout_limit=args.consecutive_timeout_limit,
                    cooc_process_workers=args.cooc_process_workers,
                    backbone_process_workers=args.backbone_process_workers,
                )

            t_bucket = time.time() - t_bucket_start

            if bucket_result is None:
                results["sizes"][bucket][model_name] = {"error": "evaluation failed"}
                print(f"  [{model_name}] Evaluation failed.")
            else:
                bucket_result["bucket_wall_time"] = round(t_bucket, 2)
                results["sizes"][bucket][model_name] = bucket_result

                print(f"  [{model_name}] Done in {t_bucket:.1f}s | "
                      f"solved={bucket_result['num_solved']} "
                      f"timed_out={bucket_result['num_timed_out']} "
                      f"skipped={bucket_result['num_skipped']} | "
                      f"avg_dec={bucket_result['avg_decisions']} "
                      f"avg_time={bucket_result['avg_time']}")

        # Save after every bucket so results aren't lost
        with open(args.out_file, "w") as f:
            json.dump(results, f, indent=2)
        print(f"\n  [Saved intermediate results to {args.out_file}]")

    # -----------------------------------------------------------------------
    # Final summary
    # -----------------------------------------------------------------------
    print("\n\n" + "=" * 70)
    print("FINAL SUMMARY")
    print("=" * 70)
    header = f"{'Bucket':<12}" + "".join(f"{m:<22}" for m in active_models)
    print(header)
    print("-" * len(header))

    for bucket in buckets:
        row = f"{bucket:<12}"
        for model_name in active_models:
            r = results["sizes"][bucket].get(model_name, {})
            if "error" in r:
                row += f"{'ERROR':<22}"
            elif r:
                row += f"{r['num_solved']}S/{r['num_timed_out']}T/{r['num_skipped']}SK  "
            else:
                row += f"{'N/A':<22}"
        print(row)

    print(f"\nFull results saved to: {args.out_file}")
    print("=" * 70)


if __name__ == "__main__":
    main()
